---
- name: restart node_exporter
  ansible.builtin.systemd:
    name: node_exporter
    daemon_reload: yes
    state: restarted

- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted