---
- name: restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    daemon_reload: yes
    state: restarted

- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
